### ISSUE TITLE
Upload Image popup for TinyMCE has overlapping buttons

### ISSUE THREAD

**Issue by kaerumy** [afterfivetech/idwfed.theme#129]
![image](https://cloud.githubusercontent.com/assets/1060743/5871832/536e3bf6-a31e-11e4-855d-305df6a8a133.png)

Also if possible to make TItle columon on the right to be wider if possible, and the browser area on left smaller.

**Comment by cindya5** [comment]
we have updates for this. upload image did not overlap when i test it on my local.
