### ISSUE TITLE
Popup for Link and Image has overlapping OK button and out of alignment radio buttons

### ISSUE THREAD

**Issue by kaerumy** [afterfivetech/idwfed.theme#130]
Radio buttons to select are not aligned.
OK button floating, not clickable sometimes.

![image](https://cloud.githubusercontent.com/assets/1060743/5871932/ba47236e-a31f-11e4-9152-c20c16ebdf5b.png)

**Comment by cindya5** [comment]
we have updates for this https://github.com/afterfivetech/idwfed.theme/commit/8ea2a2edc4ce29b0db4595d95ed58eeb255d85ca
